#!/bin/bash
echo "=== VISUALify Backend Setup ==="
echo ""
echo "1. First, create FREE cloud databases:"
echo "   - PostgreSQL: https://railway.app (click 'Start a New Project' -> 'Provision PostgreSQL')"
echo "   - Redis: https://railway.app (add Redis to same project)"
echo ""
echo "2. Copy the connection strings to backend/.env"
echo ""
echo "3. Generate security keys:"
echo "   ENCRYPTION_KEY:"
python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
echo ""
echo "   JWT_SECRET:"
python3 -c "import secrets; print(secrets.token_urlsafe(32))"
echo ""
echo "4. Run these commands:"
echo "   cd backend"
echo "   python3 -m venv venv"
echo "   source venv/bin/activate  # Windows: venv\\Scripts\\activate"
echo "   pip install -r requirements.txt"
echo "   alembic upgrade head"
echo "   uvicorn app.main:app --reload --port 8000"
echo ""
echo "5. Then start frontend: npm run dev"

